workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - default
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.grader.user"
    artifacts:
      - app/build/outputs/**/*.aab .apk
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
      
