workflows:
  android-app:
    name: Android App
    scripts:
      - ./gradlew assembleRelease
    artifacts:
      - build/outputs/**/**/*.apk
    environment:
      android_signing:
        - default
